### PR TITLE
Restrict archived users to write progress of a task

### LINKED ISSUE #2393: Bug: Archived users can write progress of a task
### Issue Description

Users who are not in discord at the moment able to write progress of task leading to unexpected behaviour.
### Expected Behavior

Users who are in discord and authenticated in RDS should only be able to write progress of a task.

### Current Behavior

Archived users can write progress of a task.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
- Any user, authenticated to RDS can go to status site and write progress of a task

### Screenshot
Image

Image

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

<!-- 
Thank you for contributing to our project! We appreciate your help in improving it.
--

### PR DESCRIPTION
**Pull request by pankajjs**
Date: 25 March, 2025

Developer Name: @pankajjs 

---

## Issue Ticket Number

- Closes #2393 
## Description
This PR adds a check which restricts archived users to write progress of a task.
- The  fix is not under feature flag as this is a minor fix without breaking change which further prevent to make changes in status site to test it with dev flag.

### Documentation Updated?

- [x] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Working video</summary>

[screen-capture (3).webm](https://github.com/user-attachments/assets/2deeab8d-3138-4849-8a26-bbb242a7474c)

</details>

## Test Coverage
<details>
<summary>Screenshots</summary>
Screenshot 2025-03-25 at 4 34 13 PM
Screenshot 2025-03-25 at 4 36 59 PM

</details>

## Additional Notes
API contract PR - https://github.com/Real-Dev-Squad/website-api-contracts/pull/227

### CODE REVIEW

File: constants/progresses.ts [hunk 1]
```diff
@@ -31,4 +33,5 @@
   PROGRESS_VALID_SORT_FIELDS,
   PROGRESSES_SIZE,
   PROGRESSES_PAGE_SIZE,
+  UNAUTHORIZED_WRITE
```
[the remark this answers is not in the document]
Comment (pankajjs) [reply constants/progresses.ts]: resolved

File: controllers/progresses.js [hunk 2]
```diff
@@ -45,6 +46,13 @@ const { PROGRESS_DOCUMENT_RETRIEVAL_SUCCEEDED, PROGRESS_DOCUMENT_CREATED_SUCCEED
  */
 
 const createProgress = async (req, res) => {
+  const dev = req.query.dev === "true";
+  if (dev && !req.userData.roles.in_discord) {
+    return res.status(403).json({
+      message: UNAUTHORIZED_WRITE,
+    });
+  }
```
Comment (MayankBansal12) [inline controllers/progresses.js:54]: can we also add check for `archived=true`?

File: test/integration/progressesTasks.test.js [hunk 3]
```diff
@@ -40,6 +42,8 @@ describe("Test Progress Updates API for Tasks", function () {
         toFake: ["Date"],
       });
       userId = await addUser(userData[1]);
+      userId2 = await addUser(userData[18]);
+      userToken2 = authService.generateAuthToken({ userId: userId2 });
```
Comment (MayankBansal12) [inline test/integration/progressesTasks.test.js:46]: can we improve the naming here?

File: controllers/progresses.js (hunk 2 above)
Comment (pankajjs) [reply controllers/progresses.js:54]: I think one check is enough. No need for extra check for same purpose.

File: test/integration/progressesTasks.test.js (hunk 3 above)
Comment (pankajjs) [reply test/integration/progressesTasks.test.js:46]: what is your suggestion?

Comment (pankajjs) [reply test/integration/progressesTasks.test.js]: resolved

File: controllers/progresses.js [hunk 4]
```diff
@@ -45,6 +46,13 @@ const { PROGRESS_DOCUMENT_RETRIEVAL_SUCCEEDED, PROGRESS_DOCUMENT_CREATED_SUCCEED
  */
 
 const createProgress = async (req, res) => {
+  const dev = req.query.dev === "true";
+  if (dev && !req.userData.roles.in_discord) {
```
Comment (AnujChhikara) [inline controllers/progresses.js:50]: I have a doubt: Why can't we check if archived is true? In the PR description, you mentioned that the goal is to restrict archived users.

Comment (pankajjs) [reply controllers/progresses.js:50]: when user leaves discord, the in_discord becomes false and archived becomes true. So we can use any role to restrict the user to make a write request.
Considering that I thought in_discord role is more suitable.

Comment (Achintya-Chatterjee) [inline controllers/progresses.js:50]: We should use `archived `: `true` instead of `in_discord`

**Review by Achintya-Chatterjee — CHANGES_REQUESTED** [review]

File: controllers/progresses.js (hunk 4 above)
Comment (pankajjs) [reply controllers/progresses.js]: Resolved

**Review by MayankBansal12 — APPROVED** [review]

File: controllers/progresses.js [hunk 5]
```diff
@@ -45,6 +46,13 @@ const { PROGRESS_DOCUMENT_RETRIEVAL_SUCCEEDED, PROGRESS_DOCUMENT_CREATED_SUCCEED
  */
 
 const createProgress = async (req, res) => {
+  const dev = req.query.dev === "true";
+  if (dev && req.userData.roles.archived) {
+    return res.status(403).json({
+      message: UNAUTHORIZED_WRITE,
+    });
+  }
+
```
Comment (AnujChhikara) [inline controllers/progresses.js:55]: Instead of this approach, can we use the authorizedRoles middleware to handle the authorization?

**Review by AnujChhikara — DISMISSED** [review]

**Review by Achintya-Chatterjee — DISMISSED** [review]

File: controllers/progresses.js [hunk 6]
```diff
@@ -45,6 +46,12 @@ const { PROGRESS_DOCUMENT_RETRIEVAL_SUCCEEDED, PROGRESS_DOCUMENT_CREATED_SUCCEED
  */
 
 const createProgress = async (req, res) => {
+  if (req.userData.roles.archived) {
+    return res.status(403).json({
```
Comment (AnujChhikara) [inline controllers/progresses.js:50]: Can we use forbidden from the http-errors library here to maintain consistency with error handling across the codebase?

Comment (pankajjs) [reply controllers/progresses.js:50]: hi @AnujChhikara you want this- 
` return res.boom.forbidden()`

Comment (AnujChhikara) [reply controllers/progresses.js:50]: yes

**Review by AnujChhikara — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]
