### PR TITLE
Modifies /members to return only unarchived users (by default)

### LINKED ISSUE #601: Archived members data not working
## After archiving a member (In database): 
image
## In fixture: 
https://github.com/Real-Dev-Squad/website-backend/blob/cc9476dec38137093f7108bcd2566b4bb5b99053/test/fixtures/user/user.js#L112-L117

### PR DESCRIPTION
**Pull request by samarpan1738**
* Added a new role archived in ROLES constant

* Added a query param includeArchived(default value false)

* By default only unarchived users are returned. We can use includeArchived = true flag to get all users

* Updated and added integration test for /members endpoint

* Updated swagger doc for /members endpoint

* Rename all occurrences of archivedMember to archived

Closes #601 

Please follow the merge order specified here : https://github.com/Real-Dev-Squad/website-backend/issues/672

### CODE REVIEW

File: controllers/members.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ const ERROR_MESSAGE = "Something went wrong. Please try again or contact admin";
 
 const getMembers = async (req, res) => {
   try {
-    const allUsers = await members.fetchUsers();
+    const allUsers = await members.fetchUsers(req.query);
```
Comment (ankushdharkar) [inline controllers/members.js:17]: Is this XSS-safe?

File: models/members.js [hunk 2]
```diff
@@ -5,21 +5,25 @@
...
-const fetchUsers = async () => {
+const fetchUsers = async (queryParams = {}) => {
   try {
     const snapshot = await userModel.get();
-
     const allMembers = [];
 
+    let { includeArchived } = queryParams;
+    if (includeArchived === "true") includeArchived = true;
+    else includeArchived = false;
```
Comment (ankushdharkar) [inline models/members.js:21]:
```suggestion
    let { showArchived } = queryParams;
    cosnt includeArchived = showArchived === "true";
```

File: models/members.js [hunk 3]
```diff
@@ -5,21 +5,25 @@
...
+
     if (!snapshot.empty) {
       snapshot.forEach((doc) => {
         const memberData = doc.data();
+        if (!includeArchived && memberData?.roles && memberData.roles[ROLES.ARCHIVED] === true) return;
```
Comment (ankushdharkar) [inline models/members.js:26]: Instead of fetching everything and then removing archived users, can we write a firestore query such that we only fetch non-archived users in the first place.
Imagine if there are 100 non-archived users and 10000 archived users. We would have paid for 10100 calls, and used only a small portion of it.
Every DB/firestore read costs us.

File: test/fixtures/user/user.js [hunk 4]
```diff
@@ -112,7 +112,7 @@ module.exports = () => {
       status: "active",
       roles: {
         app_owner: true,
-        archivedMember: true,
+        archived: true,
```
Comment (ankushdharkar) [inline test/fixtures/user/user.js:115]: Thank you!

**Review by ankushdharkar — CHANGES_REQUESTED** [review]

File: models/members.js (hunk 3 above)
Comment (samarpan1738) [reply models/members.js:26]: Even with index we can't query for unarchived users if roles or archived field is absent https://firebase.google.com/docs/firestore/query-data/queries#limitations

Also there's an index for map fields by default
https://firebase.google.com/docs/firestore/query-data/index-overview#automatic_indexing

File: models/members.js (hunk 2 above)
Comment (samarpan1738) [reply models/members.js]: Change done

File: test/fixtures/user/user.js (hunk 4 above)
Comment (samarpan1738) [reply test/fixtures/user/user.js:115]: Welcome

File: controllers/members.js (hunk 1 above)
Comment (samarpan1738) [reply controllers/members.js:17]: I think this is safe from XSS since the value of the query param won't be going in the response and further to the HTML output.
Also if there were some other query parameter also being used for this api endpoint e.g. private which we think can be misused by some user then we need to restrict the it's usage by setting some role based authorisation.

Comment (samarpan1738) [reply controllers/members.js:17]: Added validation middleware to validate the query params for the /members endpoint

File: models/members.js (hunk 3 above)
Comment (samarpan1738) [reply models/members.js]: Resolves #651

Comment (alishvagadiya) [reply models/members.js]: What is the full form of DNE hear?

Comment (alishvagadiya) [reply models/members.js]: > What is the full form of DNE hear?

DNE - does not exist

File: test/fixtures/user/user.js [hunk 5]
```diff
@@ -132,7 +132,7 @@ module.exports = () => {
       status: "active",
       roles: {
         member: true,
-        archivedMember: true,
+        archived: false,
```
Comment (alishvagadiya) [inline test/fixtures/user/user.js:135]: Why is value also changed with a key name?

File: test/integration/members.test.js [hunk 6]
```diff
@@ -22,6 +22,10 @@ const nonSuperUser = userData[0];
 const userDoesNotExists = userData[1];
 const userToBeArchived = userData[3];
 const userAlreadyArchived = userData[5];
+const userWithRolesObjectWithoutArchivedProperty = userData[0];
+const userWithoutRolesObject = userData[1];
+const userWithRolesObjectWithArchivedTrue = userData[5];
+const userWithRolesObjectWithArchivedFalse = userData[6];
```
Comment (alishvagadiya) [inline test/integration/members.test.js:28]: short variable name from the long variable name.

**Review by alishvagadiya — CHANGES_REQUESTED** [review]
Look into review comments for changes.

File: test/fixtures/user/user.js (hunk 5 above)
Comment (samarpan1738) [reply test/fixtures/user/user.js:135]: I wanted the value false for a test

File: models/members.js [hunk 7]
```diff
@@ -5,21 +5,24 @@
...
 
-const fetchUsers = async () => {
+const fetchUsers = async (queryParams = {}) => {
   try {
     const snapshot = await userModel.get();
-
     const allMembers = [];
 
+    let { showArchived } = queryParams;
+    showArchived = showArchived === "true";
```
[the remark this answers is not in the document]
Comment (samarpan1738) [reply models/members.js:20]: Query params are always of type string. 
In validation middleware I have used joi.boolean() in non-strict mode which checks for "true" or "false" or true or false
In model showArchived will be a string

File: test/integration/members.test.js (hunk 6 above)
Comment (samarpan1738) [reply test/integration/members.test.js:28]: Sure. We can shorten them a bit. Done that in the later PR https://github.com/Real-Dev-Squad/website-backend/pull/654

File: test/integration/members.test.js [hunk 8]
```diff
@@ -69,8 +105,30 @@ describe("Members", function () {
           expect(res.body).to.be.a("object");
           expect(res.body.message).to.equal("Members returned successfully!");
           expect(res.body.members).to.be.a("array");
-          expect(res.body.members[0].roles.member).to.eql(true);
+          expect(res.body.members.length).to.be.equal(unarchivedUsersGithubIds.length);
+          const memberGithubIds = res.body.members.map((member) => member.github_id);
+          expect(memberGithubIds).to.include.all.members(unarchivedUsersGithubIds);
+          expect(memberGithubIds).to.not.include.any.members(archivedUsersGithubIds);
```
Comment (ankushdharkar) [inline test/integration/members.test.js:111]: 🧑‍🍳 Awesome!

**Review by ankushdharkar — APPROVED** [review]
