### PR TITLE
fix: honor `OOO` grace window in missed updates flow

### LINKED ISSUE #2489: Fix: Returning `OOO` users are incorrectly tagged with missed updates role
### Issue Description

Users returning from an approved Out-of-Office (OOO) period are still being flagged for missed task updates. When `callDiscordNicknameBatchUpdateHandler` detects no nickname failures, the worker invokes `addMissedUpdatesRoleHandler`, which reads `/tasks/users/discord?q=status:missed-updates -days-count:3`. The backend endpoint delegates to `getMissedProgressUpdatesUsers` (`models/discordactions.js`), which iterates over tasks older than the date gap and only excludes users whose current status is OOO (`userStatus.currentStatus.state === userState.OOO`). If the worker toggles the `env.FF_CRON_DISCORD_KEY_PAIR_FLOW === 'true'`, a newly returned user whose status has already flipped to `ACTIVE` is no longer filtered out and is therefore re-tagged despite having an `OOO` window covering the same gap.

The proposed change will:
- Teach `getMissedProgressUpdatesUsers` to ignore users whose recent future/current status history includes an OOO window overlapping the evaluation gap.
- Ensure users finishing an approved OOO period are not counted toward the negligent “missed updates” list while still away or immediately upon return.
- Keep role assignment logic intact for genuinely negligent users.

### Expected Behaviour

- Users with an approved `OOO` request covering the evaluation period must not receive the missed-updates Discord role after their return.
- Users without an overlapping `OOO` period continue to be eligible for the missed-updates role.
- If a user tries to access another user's intro data without superuser privileges, they should receive a 403 "You're not authorised to view this page" response.
- The cron job and backend metrics remain accurate (no false positives, no change to successful filtering of unevaluated tasks).

### Current Behaviour

- After returning from `OOO`, a user’s status flips back to `ACTIVE`.
- `getMissedProgressUpdatesUsers` only checks the current status; past/future `OOO` windows are ignored.
- The worker re-tags the returning user for missed updates even though the lapse occurred during their approved OOO.

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1.  Submit and approve an OOO request (via `/requests` and `/users/status` flow) for dates that fully cover the next three days.
2.  Allow the user status to flip back to `ACTIVE` once the `OOO` end date passes.
3.  Observe the `cron-jobs` Cloudflare worker executing `syncApiHandler` and subsequently `addMissedUpdatesRoleHandler`.
4.  Check Discord roles or API response; the user is granted the missed-updates role even though their lack of updates occurred during `OOO`.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information

Relevant code paths:
- `cron-jobs/src/handlers/scheduledEventHandler.ts` (`addMissedUpdatesRoleHandler`)
- `cron-jobs/src/services/rdsBackendService.ts` → `/tasks/users/discord`
- `website-backend/models/discordactions.js`→ `getMissedProgressUpdatesUsers`
- `website-backend/models/userStatus.js`→ `updateAllUserStatus`, `addFutureStatus`

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by Achintya-Chatterjee**
Date: `11 November, 2025`

Developer Name: @Achintya-Chatterjee 

---

## Issue Ticket Number

- Closes #2489
## Description

- persist lastOooUntil when users leave OOO across status mutations and reconciler
- backfill historical userStatus documents with a lastOooUntil timestamp
- filter missed updates candidates using the persisted grace-period cutoff
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [x] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/a4096ea4-d99d-4403-bd7d-e55fe4b1f868

Screenshot 2025-11-15 at 00 12 46

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Screenshot 2025-11-15 at 01 09 01
Screenshot 2025-11-15 at 01 12 13
Screenshot 2025-11-15 at 01 05 34

</details>

## Additional Notes

This PR is following a stack PR approach, so #2502 will be merged into this before this PR can be merged into develop

### CODE REVIEW

File: models/discordactions.js [hunk 1]
```diff
@@ -1083,9 +1090,18 @@ const getMissedProgressUpdatesUsers = async (options = {}) => {
...
       const discordUserData = discordUserMap.get(userData.discordId);
       const isDiscordMember = !!discordUserData;
+      const normalizedLastOooUntil = normalizeTimestamp(userData.lastOooUntil);
+      const isWithinGracePeriod = normalizedLastOooUntil !== null && normalizedLastOooUntil >= gracePeriodCutoff;
+
+      if (userData.latestProgressCount === 0 && (userData.isOOO || isWithinGracePeriod)) {
+        stats.filteredByOoo++;
+        usersMap.delete(userId);
+        continue;
+      }
```
[the remark this answers is not in the document]
Comment (Achintya-Chatterjee) [reply models/discordactions.js]: resolved this, thanks for the review

File: utils/userStatus.js [hunk 2]
```diff
@@ -2,6 +2,63 @@ const { NotFound } = require("http-errors");
...
 const { convertTimestampToUTCStartOrEndOfDay } = require("./time");
 
+/**
+ * Normalizes various timestamp representations into a millisecond number.
+ * Returns null when the value is empty or cannot be parsed into a finite timestamp.
+ *
+ * @param {number|string|admin.firestore.Timestamp|undefined|null} value - Timestamp in different formats.
+ * @returns {number|null} Normalized timestamp in milliseconds or null if invalid.
+ */
+const normalizeTimestamp = (value) => {
```
Comment (MayankBansal12) [inline utils/userStatus.js]: isn't there a util already defined to normalize timestamp?
if yes, why are we redefining it here?

File: utils/userStatus.js [hunk 3]
```diff
@@ -2,6 +2,63 @@ const { NotFound } = require("http-errors");
...
+  if (value === undefined || value === null) {
+    return null;
+  }
```
Comment (MayankBansal12) [inline utils/userStatus.js]:
```suggestion
  if (value == null) {
    return null;
  }
```

File: utils/userStatus.js [hunk 4]
```diff
@@ -2,6 +2,63 @@ const { NotFound } = require("http-errors");
...
+ * @param {number|undefined} params.fallbackTimestamp - Optional fallback timestamp to use when `previousUntil` is invalid.
+ * @returns {number|null|undefined} Millisecond timestamp when leaving OOO, null when entering OOO,
+ * or undefined when no change to `lastOooUntil` is required.
+ */
+const resolveLastOooUntil = ({ previousState, previousUntil, nextState, fallbackTimestamp }) => {
+  if (nextState === userState.OOO) {
+    return null;
+  }
+
+  if (previousState === userState.OOO && nextState && nextState !== userState.OOO) {
```
Comment (MayankBansal12) [inline utils/userStatus.js]: there's already if check above to compare nextState and userState so do we really need to compare again?

File: utils/userStatus.js [hunk 5]
```diff
@@ -134,6 +190,15 @@ const updateCurrentStatusToState = async (collection, latestStatusData, newState
...
     },
   };
+  const lastOooUntilUpdate = resolveLastOooUntil({
+    previousState,
+    previousUntil,
+    nextState: newState,
+    fallbackTimestamp: currentTimeStamp,
+  });
+  if (lastOooUntilUpdate !== undefined) {
+    updatedStatusData.lastOooUntil = lastOooUntilUpdate;
```
Comment (MayankBansal12) [inline utils/userStatus.js]: if `lastOooUntilUpdate` is null, then we are going to update value in DB?

File: utils/userStatus.js [hunk 6]
```diff
@@ -2,6 +2,63 @@ const { NotFound } = require("http-errors");
...
+ * @returns {number|null|undefined} Millisecond timestamp when leaving OOO, null when entering OOO,
+ * or undefined when no change to `lastOooUntil` is required.
+ */
+const resolveLastOooUntil = ({ previousState, previousUntil, nextState, fallbackTimestamp }) => {
+  if (nextState === userState.OOO) {
+    return null;
+  }
+
+  if (previousState === userState.OOO && nextState && nextState !== userState.OOO) {
+    return normalizeTimestamp(previousUntil) ?? fallbackTimestamp ?? Date.now();
```
[the remark this answers is not in the document]
Comment (Achintya-Chatterjee) [reply utils/userStatus.js]: Yes, it’s optional metadata (`updatedAt`). We now normalise it too, so only valid timestamps propagate; otherwise, we fall back to `Date.now()`.

File: utils/userStatus.js [hunk 7]
```diff
@@ -2,6 +2,63 @@ const { NotFound } = require("http-errors");
...
+  }
+
+  return undefined;
```
[the remark this answers is not in the document]
Comment (Achintya-Chatterjee) [reply utils/userStatus.js]: Yes, that difference is intentional. `null` means `please clear the stored value` (`when someone goes into OOO`). `undefined` means `don’t touch what’s already in Firestore` because the transition doesn’t affect `lastOooUntil`. The callers only write when we return something other than `undefined`, so the distinction lets us clear the field versus leaving it alone.
