### PR TITLE
Fix/add created at updated at in task request task creation

### LINKED ISSUE #1770: Add createdAt and updatedAt when task is being created after approval of task-request
### Description

Currently createdAt and updatedAt are not being added/updated when the task is created/updated for the task request

Add createdAt/updatedAt fields when the task is being created/updated after approval of the task request

### PR DESCRIPTION
**Pull request by prakashchoudhary07**
## Issue Ticket Number:- 
- Closes #1770

## Description: 
Add createdAt and updatedAt fields when the task is being created after approval of the task request

Is Under the Feature Flag 
- [x] Yes
- [ ] No

Database changes
- [x] Yes
- [ ] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)
- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [ ] Yes
- [x] No

### Add relevant Screenshot below ( e.g test coverage etc. )
- 1. 
image

- 2.
image

- 3. 
image

### CODE REVIEW

**Review by heyrandhir — DISMISSED** [review]

**Review by vinit717 — APPROVED** [review]

File: utils/time.js [hunk 1]
```diff
@@ -83,12 +83,21 @@ const convertTimestampToUTCStartOrEndOfDay = (timestamp, isEndOfDay = false) =>
   return currTime.getTime();
 };
 
+/**
+ * Returns Current Epoch time stamp
+ * @returns {EpochTimeStamp}: Current Epoch time
+ */
+const getCurrentEpochTime = () => {
```
Comment (Ajeyakrishna-k) [inline utils/time.js:90]: There is no information of whether this returns time in seconds or milliseconds

**Review by Ajeyakrishna-k — APPROVED** [review]
