### PR TITLE
Remove orderBy from self tasks api

### LINKED ISSUE #1254: Fail tasks self api
Currently, self tasks API call uses orderBy to sort the query based on startedOn , but in some tasks data there is no field startedOn so orderBy is failing to get the tasks

image

### PR DESCRIPTION
**Pull request by vinit717**
Closes #1254

## Overview

Currently, self API of tasks is failing because there is no field of startedOn in some tasks so for the temporary solution it is been removed for a permanent solution the issue is mentioned below.

image

## Later work
- https://github.com/Real-Dev-Squad/website-backend/issues/1257

### CODE REVIEW

**Comment by sahsisunny** [comment]
@vinit717 we have to also remove the indexes?

**Review by sahsisunny — DISMISSED** [review]

**Review by isVivek99 — DISMISSED** [review]

File: models/tasks.js [hunk 1]
```diff
@@ -253,7 +253,8 @@ const fetchUserTasks = async (username, statuses = [], field, order) => {
           .where("participants", "array-contains", userId)
           .orderBy(field, order)
           .get();
-        featureTasksSnapshot = await tasksModel.where("assignee", "==", userId).orderBy(field, order).get();
+        featureTasksSnapshot = await tasksModel.where("assignee", "==", userId).get();
```
Comment (heyrandhir) [inline models/tasks.js:256]: rather than changing here I suggest we do it here https://github.com/Real-Dev-Squad/website-backend/blob/7e1fe072f031556f64b65320dbb53c4a769ba3da/models/tasks.js#L359. if we don't pass `field` it will go to the else loop

Comment (vinit717) [reply models/tasks.js]: done

File: models/tasks.js [hunk 2]
```diff
@@ -355,7 +355,8 @@ const fetchSkillLevelTask = async (userId) => {
  * @returns {Promise<tasks>|Array}
  */
 const fetchSelfTasks = async (username) => {
-  return await fetchUserTasks(username, [], "startedOn", "desc");
+  return await fetchUserTasks(username, []);
+  // removed startedOn as now task is not have field startedOn
```
Comment (heyrandhir) [inline models/tasks.js:359]: Can you mention the Ticket No here in the comment as well. will be easy to track

**Review by heyrandhir — CHANGES_REQUESTED** [review]

File: models/tasks.js (hunk 2 above)
Comment (heyrandhir) [reply models/tasks.js:359]: https://github.com/Real-Dev-Squad/website-backend/issues/1257 & https://github.com/Real-Dev-Squad/website-backend/issues/1256

Comment (heyrandhir) [inline models/tasks.js:359]:
```suggestion
Removed `startedOn` field since we are getting issues with some of the documents in the tasks collection as some of the documents dont have `startedOn` present. 
```

**Review by heyrandhir — CHANGES_REQUESTED** [review]

**Review by sahsisunny — DISMISSED** [review]

File: models/tasks.js (hunk 2 above)
Comment (vinit717) [reply models/tasks.js:359]: I had mentioned

**Review by heyrandhir — APPROVED** [review]

**Review by kotesh-arya — APPROVED** [review]
